### ISSUE TITLE
after UPDATE on API key (android) -> An error occured :(

### ISSUE THREAD

**Issue by orlandosim** [vernu/textbee#15]
Hey, 

I installed the textbee app (2.3.1) on my old huawei android 7 tablet with active FCM (it's a device with google android).
The issue in my case is that after I press the UPDATE button on API key I got the message "An error occured :(". nothin else.
Is there a way to deeper check where the problem is? do you have an idea about this issue?

Many Thanks!
Regards
Simon

**Comment by vernu** [comment]
@orlandosim could you try generating a new API Key and scanning the QR instead of manually entering the key and clicking update?
Also make sure you have a working internet connection when you do that/

**Comment by orlandosim** [comment]
It's unfortunately the same situation. Same error message. 
I tried it via mobile internet as well wifi.

**Comment by x011** [comment]
I get the same error. How to debug/fix this?

**Comment by x011** [comment]
I fixed this by force closing the app and trying again.

**Comment by orlandosim** [comment]
@x011, for me still the same issue. i tried to force close the app as well to reinstall it. in both situations with scanning of the code is still not working :(

**Comment by vernu** [comment]
> @x011, for me still the same issue. i tried to force close the app as well to reinstall it. in both situations with scanning of the code is still not working :(

@orlandosim please send your email address associated with your account and the device id (if there is one) via [textbee.dev@gmail.com](mailto:textbee.dev@gmail.com) and I'll investigate further.

**Comment by orlandosim** [comment]
Thanks for all your support. Maybe the old Android version was the problem... Now I'm running your app on a newer device. It's working!
Many Thanks! Regards Simon
